version: "3.7"


services:
  site:
    build: .
    restart: always
    environment:
      - APP_URL=http://localhost
      - APP_DEBUG=True
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_DATABASE=db
      - PRODUCT=False
    volumes:
      - ./public:/var/www/public
      - ./app:/var/www/app
      - ./config:/var/www/config
      - ./routes:/var/www/routes
      - ./database:/var/www/database
      - ./storage:/var/www/storage
      - ./resources:/var/www/resources
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - db
    container_name: site

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '306:3306'
    volumes:
      - ./my-db:/var/lib/mysql
    container_name: db  

  php_my_admin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "8001:80"
    container_name: php_my_admin

  nginx:
    image: nginx:alpine
    container_name: wurstach
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/public
      - ./storage:/var/www/storage
      - ./docker/nginx/nginx.debug.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - site
